"use client";

import { useEffect, useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";

type User = { id: string; display_name: string | null; account_status: string; created_at: string };
type Plan = { id: string; name: string; monthly_blocks: number };
type Subscription = { user_id: string; plan_id: string | null; blocks_available: number; blocks_used: number; status: string };
type Invitation = { id: string; expires_at: string; used_at: string | null; created_at: string; disabled_at: string | null };

export default function ManageUsers() {
  const [users, setUsers] = useState<User[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [subs, setSubs] = useState<Subscription[]>([]);
  const [invitations, setInvitations] = useState<Invitation[]>([]); const [generatedCode, setGeneratedCode] = useState(""); const [codeExpiresAt, setCodeExpiresAt] = useState(""); const [notice, setNotice] = useState(""); const [generating, setGenerating] = useState(false);
  const c = createBrowserSupabaseClient();
  async function token() { const { data } = await c.auth.getSession(); return data.session?.access_token || ""; }
  async function load() { const authToken = await token(); const [u, p, s, response] = await Promise.all([c.from("profiles").select("id,display_name,account_status,created_at").eq("role", "athlete"), c.from("subscription_plans").select("id,name,monthly_blocks").eq("active", true), c.from("user_subscriptions").select("user_id,plan_id,blocks_available,blocks_used,status"), fetch("/api/admin/invitations", { headers: { Authorization: `Bearer ${authToken}` } })]); setUsers((u.data || []) as User[]); setPlans((p.data || []) as Plan[]); setSubs((s.data || []) as Subscription[]); const payload = await response.json() as { invitations?: Invitation[] }; if (response.ok) setInvitations(payload.invitations || []); }
  useEffect(() => { void load(); }, []);
  async function operate(body: unknown) { const response = await fetch("/api/admin/operations", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json() as { error?: string }).error || "No pudimos completar la operación."); }
  async function suspend(user: User) { await operate({ action: "athlete.status", id: user.id, accountStatus: user.account_status === "suspended" ? "active" : "suspended" }); void load(); }
  async function setPlan(userId: string, planId: string) { if (!planId) return; await operate({ action: "subscription.assign", athleteId: userId, planId }); void load(); }
  async function generateInvitation() { setGenerating(true); setNotice(""); setGeneratedCode(""); try { const response = await fetch("/api/admin/invitations", { method: "POST", headers: { Authorization: `Bearer ${await token()}` } }); const payload = await response.json() as { ok?: boolean; error?: string; invitation?: { code: string; expiresAt: string } }; if (!response.ok || !payload.ok || !payload.invitation) throw new Error(payload.error || "No pudimos generar el código."); setGeneratedCode(payload.invitation.code); setCodeExpiresAt(payload.invitation.expiresAt); setNotice("Copiá el código ahora: por seguridad no vuelve a mostrarse."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos generar el código."); } finally { setGenerating(false); } }
  async function manageInvitation(id: string, action: "disable" | "extend") { setNotice(""); try { const response = await fetch("/api/admin/invitations", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify(action === "extend" ? { action, id, hours: 24 } : { action, id }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "No pudimos actualizar el código."); setNotice(action === "disable" ? "Código suspendido." : "Vigencia extendida por 24 horas."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos actualizar el código."); } }
  const date = (value: string) => new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
  const invitationStatus = (invitation: Invitation) => invitation.disabled_at ? "Suspendido" : invitation.used_at ? "Usado" : new Date(invitation.expires_at) <= new Date() ? "Vencido" : "Disponible";
  return <main className="admin-users"><header><span>ADMINISTRACIÓN · USUARIOS</span><h1>Usuarios y suscripciones</h1><p>Gestioná acceso, planes, bloques y códigos de invitación.</p></header><section className="invitation-panel"><div><small>ACCESO POR INVITACIÓN</small><h2>Códigos de alta</h2><p>Generá un código único, válido por 72 horas. Aksis guarda solamente su hash seguro.</p></div><button className="primary-button" type="button" disabled={generating} onClick={() => void generateInvitation()}>{generating ? "Generando…" : "+ Generar código"}</button>{generatedCode && <article className="generated-invitation"><span>CÓDIGO NUEVO</span><strong>{generatedCode}</strong><small>Vence {date(codeExpiresAt)}</small></article>}{notice && <p className="invitation-notice">{notice}</p>}<div className="invitation-history"><div className="invitation-history-head"><b>Estado</b><b>Creado</b><b>Vence</b><b>Acciones</b></div>{invitations.map((invitation) => { const status = invitationStatus(invitation); const canExtend = status === "Disponible" || status === "Vencido"; return <article key={invitation.id}><span className={`invitation-status ${status.toLowerCase()}`}>{status}</span><time>{date(invitation.created_at)}</time><time>{date(invitation.expires_at)}</time><aside>{canExtend && <button type="button" onClick={() => void manageInvitation(invitation.id, "extend")}>+24 h</button>}{status === "Disponible" && <button className="invitation-suspend" type="button" onClick={() => void manageInvitation(invitation.id, "disable")}>Suspender</button>}</aside></article>; })}{!invitations.length && <p className="invitation-history-empty">Todavía no hay códigos generados.</p>}</div></section><section><div className="admin-users-head"><b>Usuario</b><b>Estado</b><b>Plan y bloques</b><b>Acciones</b></div>{users.map(user => { const sub = subs.find(item => item.user_id === user.id); return <article key={user.id}><strong>{user.display_name || "Sin nombre"}<small>Alta: {new Date(user.created_at).toLocaleDateString("es-AR")}</small></strong><span>{user.account_status === "suspended" ? "Suspendido" : "Activo"}</span><label><select value={sub?.plan_id || ""} onChange={event => void setPlan(user.id, event.target.value)}><option value="">Sin plan</option>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name} · {plan.monthly_blocks} bloques</option>)}</select><small>{sub ? `${sub.blocks_used} usados · ${sub.blocks_available} disponibles` : "Sin suscripción"}</small></label><button onClick={() => void suspend(user)}>{user.account_status === "suspended" ? "Reactivar" : "Suspender"}</button></article>; })}{!users.length && <p>Aún no hay atletas registrados.</p>}</section></main>;
}
