"use client";
import { FormEvent, useEffect, useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";

type Configuration = { id:string; provider:"gemini"|"openai"|"openrouter"; model:string; system_prompt:string; input_price_per_million_usd:number; output_price_per_million_usd:number };
const defaultPrompt = "Sos Aksis, coach ontológico especializado en deportistas adultos. Guiá con preguntas abiertas, breves y precisas. Diferenciá hechos de juicios e integrá lenguaje, emoción y corporalidad. No des consejos directivos ni diagnósticos. Ante situaciones sensibles, suspendé el coaching y derivá a recursos de ayuda.";
const models = { gemini:["gemini-2.5-flash","gemini-2.5-pro"], openai:["gpt-5-mini","gpt-5"], openrouter:["google/gemini-2.5-flash","openai/gpt-5-mini"] };

export default function AgentAdminPage(){
 const [config,setConfig]=useState<Configuration|null>(null); const [notice,setNotice]=useState(""); const [saving,setSaving]=useState(false); const client=createBrowserSupabaseClient();
 useEffect(()=>{void client.from("agent_configurations").select("*").eq("is_active",true).maybeSingle().then(({data})=>setConfig(data as Configuration|null))},[]);
 const value=config||{id:"",provider:"gemini" as const,model:"gemini-2.5-flash",system_prompt:defaultPrompt,input_price_per_million_usd:0,output_price_per_million_usd:0};
 function set<K extends keyof typeof value>(key:K,next:(typeof value)[K]){setConfig({...value,[key]:next} as Configuration)}
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setNotice("");const payload={provider:value.provider,model:value.model,system_prompt:value.system_prompt,input_price_per_million_usd:Number(value.input_price_per_million_usd)||0,output_price_per_million_usd:Number(value.output_price_per_million_usd)||0,is_active:true};const result=value.id?await client.from("agent_configurations").update(payload).eq("id",value.id).select().single():await client.from("agent_configurations").insert(payload).select().single();if(result.error)setNotice(`No se pudo guardar: ${result.error.message}`);else{setConfig(result.data as Configuration);await client.from("agent_prompt_versions").insert({configuration_id:result.data.id,prompt:value.system_prompt});setNotice("Configuración guardada. El próximo mensaje usará este prompt y modelo.")}setSaving(false)}
 return <main className="admin-view agent-view"><span>AGENTE DE AKSIS · CONFIGURACIÓN</span><h1>Configuración del agente</h1><p>Los modelos y el prompt se aplican al próximo turno. Las claves API no se guardan aquí: permanecen como variables privadas del servidor.</p><form className="agent-config-form" onSubmit={save}>
 <section><h2>Proveedor y modelo</h2><div className="agent-fields"><label>Proveedor<select value={value.provider} onChange={e=>{const provider=e.target.value as Configuration["provider"];setConfig({...value,provider,model:models[provider][0]} as Configuration)}}><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="openrouter">OpenRouter</option></select></label><label>Modelo<select value={value.model} onChange={e=>set("model",e.target.value)}>{models[value.provider].map(model=><option key={model}>{model}</option>)}</select></label></div><p className="secure-note">Credencial: administrada en el entorno seguro. Para rotarla, actualizá la variable privada de la plataforma; nunca pegues una clave en el navegador.</p></section>
 <section><h2>Costos de referencia</h2><div className="agent-fields"><label>US$ / millón de tokens de entrada<input type="number" min="0" step="0.000001" value={value.input_price_per_million_usd} onChange={e=>set("input_price_per_million_usd",Number(e.target.value))}/></label><label>US$ / millón de tokens de salida<input type="number" min="0" step="0.000001" value={value.output_price_per_million_usd} onChange={e=>set("output_price_per_million_usd",Number(e.target.value))}/></label></div><p className="secure-note">Estas tarifas se usan para estimar consumo. Verificá los precios vigentes del proveedor antes de facturar.</p></section>
 <section><h2>Prompt operativo</h2><textarea value={value.system_prompt} onChange={e=>set("system_prompt",e.target.value)} maxLength={20000}/><small>{value.system_prompt.length.toLocaleString("es-AR")} / 20.000 caracteres · se conserva una versión por cada guardado.</small></section>
 {notice&&<p className={notice.startsWith("No")?"admin-error":"admin-success"}>{notice}</p>}<button disabled={saving}>{saving?"Guardando…":"Guardar configuración"}</button></form></main>;
}
