"use client";

import { useEffect, useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import { useAksisToast } from "@/components/aksis-toast";

type RequestItem = { id: string; user_id: string; userName: string; request_type: string; status: "pending" | "in_review" | "completed" | "rejected"; details: string; requested_at: string; resolved_at: string | null; resolution_note: string | null };
const labels: Record<string, string> = { export: "Exportación", rectification: "Rectificación", erasure: "Eliminación", withdraw_consent: "Retiro de consentimiento" };

export default function PrivacyRequestsPage() {
  const [items, setItems] = useState<RequestItem[]>([]); const [loading, setLoading] = useState(true); const [active, setActive] = useState<RequestItem | null>(null); const [note, setNote] = useState(""); const { showToast } = useAksisToast();
  async function authHeaders() { const { data } = await createBrowserSupabaseClient().auth.getSession(); return { "Content-Type": "application/json", Authorization: `Bearer ${data.session?.access_token || ""}` }; }
  async function load() { setLoading(true); const response = await fetch("/api/admin/privacy-requests", { headers: await authHeaders() }); const payload = await response.json() as { requests?: RequestItem[]; error?: string }; if (!response.ok) showToast(payload.error || "No pudimos cargar las solicitudes.", "error"); else setItems(payload.requests || []); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function update(status: "in_review" | "completed" | "rejected") { if (!active) return; const response = await fetch("/api/admin/privacy-requests", { method: "PATCH", headers: await authHeaders(), body: JSON.stringify({ id: active.id, status, resolutionNote: note }) }); const payload = await response.json() as { error?: string }; if (!response.ok) return showToast(payload.error || "No pudimos actualizar la solicitud.", "error"); showToast("Solicitud actualizada y auditada.", "success"); setActive(null); setNote(""); void load(); }
  const pending = items.filter((item) => item.status === "pending" || item.status === "in_review").length;
  return <main className="admin-view privacy-admin"><header><span>OPERACIÓN · PRIVACIDAD</span><h1>Solicitudes de datos</h1><p>Revisá pedidos de exportación, rectificación, eliminación y retiro de consentimiento. El contenido de coaching y bitácora no se muestra aquí.</p></header><section className="privacy-request-summary"><b>{loading ? "—" : pending}</b><span>pendientes de revisión</span><button onClick={() => void load()}>↻ Actualizar</button></section><section className="privacy-request-list">{items.map((item) => <article key={item.id}><div><small>{labels[item.request_type] || item.request_type} · {new Date(item.requested_at).toLocaleDateString("es-AR")}</small><h2>{item.userName}</h2><p>{item.details || "Sin detalle adicional."}</p></div><span className={`privacy-request-status ${item.status}`}>{item.status === "pending" ? "Pendiente" : item.status === "in_review" ? "En revisión" : item.status === "completed" ? "Completada" : "Rechazada"}</span><button onClick={() => { setActive(item); setNote(item.resolution_note || ""); }}>Revisar</button></article>)}{!loading && !items.length && <p>No hay solicitudes registradas.</p>}</section>{active && <section className="privacy-request-modal" role="dialog" aria-modal="true" aria-label="Revisar solicitud"><div><button className="privacy-close" onClick={() => setActive(null)}>×</button><small>{labels[active.request_type] || active.request_type}</small><h2>{active.userName}</h2><p>{active.details || "Sin detalle adicional."}</p><label>Nota interna de resolución<textarea value={note} maxLength={1200} onChange={(event) => setNote(event.target.value)} placeholder="Acción realizada o motivo de la decisión…" /></label><footer><button onClick={() => void update("in_review")}>Marcar en revisión</button><button className="privacy-reject" onClick={() => void update("rejected")}>Rechazar</button><button className="admin-primary-action" onClick={() => void update("completed")}>Completar</button></footer></div></section>}</main>;
}
