import Image from "next/image";
import Link from "next/link";
import logo from "../../imagenes/minilogo.jpg";
import chatScreen from "../../Diseño/Chat/screen.png";

const pillars = [["✦", "El cuerpo", "Pilar somático", "Registrar respiración, tensión y energía para volver a tu centro."], ["♡", "La emoción", "Pilar emocional", "Dar lugar a lo que sentís, sin exigirte respuestas rápidas."], ["◌", "El lenguaje", "Pilar conversacional", "Transformar los juicios que te limitan en nuevas posibilidades."]];

export function HomeLanding() {
  return <main className="aksis-landing">
    <header className="landing-nav"><Link href="/" className="landing-brand"><Image src={logo} alt="Aksis" priority /><span><b>AKSIS</b><small>ATHLETE SANCTUARY</small></span></Link><nav><a href="#proposito">Propósito</a><a href="#pilares">Pilares</a><a href="#herramientas">Herramientas</a><a href="#membresia">Membresía</a></nav><div><Link className="landing-login" href="/access">Iniciar sesión</Link><Link className="landing-cta mini" href="/access?mode=signup">Empezar ahora</Link></div></header>
    <section className="landing-hero" id="proposito"><div className="landing-glow" /><div className="landing-eyebrow"><i /> Coaching ontológico deportivo & santuario consciente</div><h1>El rendimiento extraordinario nace desde la <em>calma interior</em>.</h1><p>AKSIS acompaña a deportistas a sincronizar cuerpo, emoción y conversación interna. Un espacio para escucharte, comprenderte y avanzar desde tu propio proceso.</p><div className="landing-actions"><Link className="landing-cta" href="/access?mode=signup">Comenzar mi experiencia</Link><a className="landing-secondary" href="#herramientas">◉ Ver cómo funciona</a></div><div className="landing-showcase"><article className="landing-breath-card"><small>MODULADOR SOMÁTICO</small><div><b>◌</b><span>Inhalá<br /><strong>4 seg</strong></span></div><p>Regulación suave antes de un momento importante.</p></article><div className="landing-phone"><Image src={chatScreen} alt="Vista de una conversación con Coach Meli en Aksis" priority /></div><article className="landing-presence-card"><span><i /> Presencia activa</span><b>Un lugar para vos</b><p>Tu proceso se construye con cuidado, sin presión y a tu propio ritmo.</p></article></div><div className="landing-domains"><span>✦ ENTRENAMIENTO SOMÁTICO</span><span>♡ INTELIGENCIA EMOCIONAL</span><span>◌ INTERPRETACIÓN CONSCIENTE</span><span>⌁ PRESENCIA & PROPÓSITO</span></div></section>
    <section className="landing-pillars" id="pilares"><header><small>FUNDAMENTOS DEL SANTUARIO</small><h2>Trascendé los bloqueos competitivos integrando tus dominios inseparables.</h2><p>El deportista no es una máquina de resultados: es un ser que observa, siente y actúa.</p></header><div>{pillars.map(([icon, title, subtitle, text]) => <article key={title}><i>{icon}</i><small>{subtitle}</small><h3>{title}</h3><p>{text}</p><footer><span>Presencia activa</span><b>→</b></footer></article>)}</div></section>
    <section className="landing-tools" id="herramientas"><header><small>HERRAMIENTAS DEL SANTUARIO</small><h2>Todo lo que necesitás para tu entrenamiento interior en una sola aplicación.</h2></header><div className="landing-tool-row"><div><span>01 · REGULACIÓN BIOLÓGICA</span><h3>Respiración consciente</h3><p>Elegí un ritmo, música opcional y guía suave para crear una pausa antes, durante o después de entrenar.</p><ul><li>Visuales que acompañan cada ciclo.</li><li>Un espacio breve para volver a tu centro.</li></ul></div><aside className="landing-breathing-demo"><div><b>4 seg</b><small>Inhalá</small></div><section><p>1. Centrado consciente <b>4 · 4 · 4 · 4</b></p><p>2. Resolución y presencia <b>4 · 2</b></p><p>3. Soltar y descansar <b>4 · 8</b></p></section></aside></div><div className="landing-tool-row reverse"><aside className="landing-journal-demo"><div><span>☁</span><b>Bitácora personal</b><small>Tu registro, en tus palabras.</small></div><p>“Pude frenar, respirar y mirar lo que me estaba pasando sin juzgarme.”</p></aside><div><span>02 · INTROSPECCIÓN VIVA</span><h3>Bitácora personal</h3><p>Registrá emociones, sensaciones, aprendizajes y momentos significativos. Volvé a ellos cuando quieras para reconocer tu recorrido.</p><ul><li>Texto, imagen y voz en un mismo espacio.</li><li>Seguimientos para profundizar una reflexión.</li></ul></div></div><div className="landing-tool-row"><div><span>03 · PRESENCIA AFECTIVA</span><h3>Coach Meli</h3><p>Un diálogo ontológico que escucha tu contexto, distingue hechos de juicios y te acompaña con preguntas que abren posibilidades.</p><blockquote>“¿Qué te gustaría que esta conversación haga posible para vos hoy?”</blockquote></div><aside className="landing-coach-demo"><header><i>◌</i><div><b>Meli</b><small>Escucha activa y coaching ontológico</small></div></header><p>¿Cómo llega hoy tu mente y tu cuerpo a este espacio?</p><p className="mine">Quiero recuperar calma antes del partido.</p><p>Podemos mirar juntos qué está pidiendo esa calma en vos.</p></aside></div></section>
    <section className="landing-membership" id="membresia"><small>ACCESO INTEGRAL</small><h2>Un santuario diseñado para tu bienestar duradero.</h2><p>Creá tu espacio y conocé las opciones de acompañamiento disponibles para tu proceso.</p><article><span>EXPERIENCIA AKSIS</span><h3>Tu espacio, a tu ritmo</h3><p>Respiración, bitácora, agenda de hitos y conversaciones con Coach Meli.</p><ul><li>Un entorno privado para tu proceso.</li><li>Herramientas centradas en cuerpo, emoción y lenguaje.</li><li>Planes configurables según tus necesidades.</li></ul><Link className="landing-cta" href="/access?mode=signup">Crear mi espacio</Link></article></section>
    <section className="landing-final"><h2>Tu cuerpo ya conoce el camino. Brindale el espacio para escucharlo.</h2><p>Elegí un alto rendimiento consciente, sin dejar tu paz interior afuera del proceso.</p><Link className="landing-secondary" href="/access?mode=signup">Crear mi espacio en AKSIS</Link></section>
    <footer className="landing-footer"><div><Image src={logo} alt="" /><b>AKSIS</b><span>© {new Date().getFullYear()} Aksis.</span></div><nav><Link href="/privacy">Privacidad</Link><Link href="/terms">Términos</Link><Link href="/access">Ingresar</Link></nav></footer>
  </main>;
}
