"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
type Entry={id:string;content:string;title:string|null;mood:string|null;goal_id:string|null;occurred_at:string}; type Goal={id:string;title:string;status:string};
const moods=[['😊','Contento'],['😔','Triste'],['💭','Preocupado'],['⚡','Entusiasmado'],['🌧️','Cansado']];
export function Journal(){const [entries,setEntries]=useState<Entry[]>([]);const [goals,setGoals]=useState<Goal[]>([]);const [query,setQuery]=useState('');const [editing,setEditing]=useState<Entry|null>(null);const [mood,setMood]=useState('');const [busy,setBusy]=useState(false);const client=createBrowserSupabaseClient();
async function load(){const {data:{user}}=await client.auth.getUser();if(!user)return location.assign('/access');const [{data:rows},{data:profile}]=await Promise.all([client.from('journal_entries').select('id,content,title,mood,goal_id,occurred_at').eq('athlete_id',user.id).order('occurred_at',{ascending:false}),client.from('athlete_profiles').select('goals_list').eq('user_id',user.id).single()]);setEntries((rows||[]) as Entry[]);const raw=Array.isArray(profile?.goals_list)?profile.goals_list:[];setGoals(raw.flatMap((item:unknown,index:number)=>typeof item==='string'?[{id:`initial-${index}`,title:item,status:'active'}]:item&&typeof item==='object'&&'title' in item&&((item as Goal).status!=='closed')?[{...(item as Goal),id:(item as Goal).id||`goal-${index}`}]:[]))}useEffect(()=>{void load()},[]);
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const content=String(f.get('content')||'').trim();if(!content)return;setBusy(true);const {data:{user}}=await client.auth.getUser();if(!user)return;const data={content,title:String(f.get('title')||'')||null,mood,goal_id:String(f.get('goal')||'')||null};let id=editing?.id;if(id)await client.from('journal_entries').update(data).eq('id',id);else {const {data:created}=await client.from('journal_entries').insert({...data,athlete_id:user.id}).select('id').single();id=created?.id}const file=f.get('photo');if(id&&file instanceof File&&file.size){const ext=file.type.split('/')[1]||'jpg';const path=`${user.id}/${id}.${ext}`;await client.storage.from('journal-media').upload(path,file,{upsert:true,contentType:file.type});await client.from('journal_media').upsert({journal_entry_id:id,athlete_id:user.id,storage_path:path,mime_type:file.type,byte_size:file.size},{onConflict:'storage_path'})}setEditing(null);setMood('');setBusy(false);void load()}
async function remove(id:string){if(!confirm('¿Borrar este registro?'))return;await client.from('journal_entries').delete().eq('id',id);void load()}
const visible=entries.filter(x=>`${x.title||''} ${x.content}`.toLowerCase().includes(query.toLowerCase()));return <main className="journal-page"><header><Link href="/app">← Volver a Mi Espacio</Link><span>{entries.length} entradas</span><h1>Bitácora personal</h1><p>Tu espacio de registro emocional, corporal y deportivo.</p></header><input className="journal-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar palabras, sensaciones o fechas…"/><section className="journal-form"><h2>{editing?'Editar registro':'Nuevo registro'}</h2><form onSubmit={save}><div className="moods">{moods.map(([icon,label])=><button className={mood===label?'selected':''} type="button" onClick={()=>setMood(label)} key={label}>{icon}<small>{label}</small></button>)}</div><input name="title" placeholder="Título (opcional)" defaultValue={editing?.title||''}/><select name="goal" defaultValue={editing?.goal_id||''}><option value="">Vincular a un objetivo (opcional)</option>{goals.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select><textarea name="content" required defaultValue={editing?.content||''} placeholder="¿Qué pasó, qué sentiste o qué querés registrar?"/><input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/><footer><button type="button" onClick={()=>{setEditing(null);setMood('')}}>Cancelar</button><button disabled={busy}>{busy?'Guardando…':'Guardar registro'}</button></footer></form></section><section className="journal-list">{visible.map(entry=><article key={entry.id}><div><span>{moods.find(m=>m[1]===entry.mood)?.[0]||'◌'} {entry.mood||'Registro'}</span><time>{new Date(entry.occurred_at).toLocaleString('es-AR')}</time></div><h3>{entry.title||'Sin título'}</h3>{entry.goal_id&&<small>Objetivo vinculado</small>}<p>{entry.content}</p><footer><button onClick={()=>{setEditing(entry);setMood(entry.mood||'')}}>Editar</button><button onClick={()=>remove(entry.id)}>Borrar</button></footer></article>)}</section></main>}
