"use client";
import { useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import { useAksisToast } from "@/components/aksis-toast";
const sports = ["Atletismo","Básquet","Ciclismo","Fútbol","Hockey","Natación","Rugby","Running","Tenis","Vóley","Otro"];
export function OnboardingFlow() {
  const { showToast } = useAksisToast();
  const [step,setStep]=useState(1); const [form,setForm]=useState<Record<string,string|string[]>>({coach:"Aksis",stage:"Competitivo",coachStatus:"no",focuses:[]});
  const set=(key:string,value:string|string[])=>setForm({...form,[key]:value});
  const toggle=(value:string)=>{const current=form.focuses as string[];set("focuses",current.includes(value)?current.filter(x=>x!==value):[...current,value]);};
  async function finish(){const c=createBrowserSupabaseClient();const {data}=await c.auth.getUser();if(!data.user)return location.assign("/access");const adult=new Date(Date.now()-18*365.25*86400000);if(new Date(String(form.birth))>adult)return showToast("Aksis está disponible para mayores de 18 años en este MVP.","info");await c.from("profiles").update({display_name:form.name}).eq("id",data.user.id);await c.from("athlete_profiles").update({date_of_birth:form.birth,sport:form.sport==="Otro"?form.otherSport:form.sport,competition_level:form.stage,province:form.province,city:form.city,organization_name:form.organization,preferred_coach_name:form.coach,focus_areas:form.focuses,focus_area_other:form.otherFocus,goals_list:[form.goal1,form.goal2,form.goal3].filter(Boolean),current_challenge:form.challenge,training_days_per_week:Number(form.days),next_event_name:form.event,next_event_date:form.eventDate||null,human_coach_status:form.coachStatus,onboarding_completed_at:new Date().toISOString()}).eq("user_id",data.user.id);location.assign("/app");}
  return <main className="onboarding-page"><section className="onboarding-shell"><p className="eyebrow">PASO {step} DE 3</p><h1>{step===1?"Tu perfil deportivo":step===2?"Tu proceso actual":"Acompañamiento humano"}</h1>
  {step===1&&<div className="form-stack"><label>¿Cómo querés que te llamemos?<input onChange={e=>set("name",e.target.value)} required/></label><label>¿Cómo querés llamar a tu coach?<input value={String(form.coach)} onChange={e=>set("coach",e.target.value)}/></label><label>Fecha de nacimiento<input type="date" onChange={e=>set("birth",e.target.value)} required/></label><label>Deporte<select onChange={e=>set("sport",e.target.value)}>{sports.map(s=><option key={s}>{s}</option>)}</select></label>{form.sport==="Otro"&&<label>Contanos cuál<input onChange={e=>set("otherSport",e.target.value)}/></label>}<label>Etapa actual<select value={String(form.stage)} onChange={e=>set("stage",e.target.value)}><option>Formación</option><option>Competitivo</option><option>Alto rendimiento</option><option>Master / recreativo con objetivos</option></select></label><label>Club, equipo, federación u organización<input onChange={e=>set("organization",e.target.value)}/></label><label>Ciudad<input onChange={e=>set("city",e.target.value)}/></label><label>Provincia<input onChange={e=>set("province",e.target.value)}/></label></div>}
  {step===2&&<div className="form-stack"><label>¿Qué te gustaría trabajar con Aksis?</label><div className="choice-grid">{["Confianza","Presión competitiva","Frustración y error","Motivación","Equilibrio entre deporte y vida","Comunicación / equipo","Otro"].map(item=><button type="button" className={(form.focuses as string[]).includes(item)?"selected":""} onClick={()=>toggle(item)} key={item}>{item}</button>)}</div>{(form.focuses as string[]).includes("Otro")&&<label>Otro foco<input onChange={e=>set("otherFocus",e.target.value)}/></label>}<label>Objetivo 1<input placeholder="Ej. disfrutar más la competencia" onChange={e=>set("goal1",e.target.value)}/></label><label>Objetivo 2<input onChange={e=>set("goal2",e.target.value)}/></label><label>Objetivo 3<input onChange={e=>set("goal3",e.target.value)}/></label><label>¿Qué situación te desafía hoy?<textarea onChange={e=>set("challenge",e.target.value)}/></label><label>Días de entrenamiento por semana<input type="number" min="0" max="7" onChange={e=>set("days",e.target.value)}/></label><label>Próximo evento<input onChange={e=>set("event",e.target.value)}/></label><label>Fecha aproximada<input type="date" onChange={e=>set("eventDate",e.target.value)}/></label></div>}
  {step===3&&<div className="form-stack"><label>¿Trabajás actualmente con un coach humano?</label>{[["no","No"],["not_ready","Sí, pero todavía no quiero vincularlo"],["later","Sí, me gustaría vincularlo más adelante"]].map(([value,label])=><button type="button" className={form.coachStatus===value?"selected":""} onClick={()=>set("coachStatus",value)} key={value}>{label}</button>)}<label>Avatar o foto de perfil (opcional)<input type="file" accept="image/png,image/jpeg,image/webp"/></label></div>}
  <div className="onboarding-actions">{step>1&&<button type="button" onClick={()=>setStep(step-1)}>Volver</button>}<button className="auth-submit" type="button" onClick={()=>step<3?setStep(step+1):finish()}>{step<3?"Continuar →":"Entrar a mi espacio →"}</button></div></section></main>;
}
