"use client";
import { useEffect, useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
type Doc = { document_key: "terms" | "privacy" | "ai_use"; version: string; title: string; content: string; content_hash: string };
export function TermsFlow() {
  const [docs, setDocs] = useState<Doc[]>([]); const [open, setOpen] = useState<string | null>(null); const [read, setRead] = useState<string[]>([]); const [checks, setChecks] = useState<string[]>([]); const [status, setStatus] = useState(""); const [aiCoaching, setAiCoaching] = useState(false); const [weeklySummary, setWeeklySummary] = useState(false); const [voice, setVoice] = useState(false); const [photoAi, setPhotoAi] = useState(false);
  useEffect(() => { const c = createBrowserSupabaseClient(); void c.auth.getUser().then(async ({ data }) => { if (!data.user) return location.assign("/access"); const { data: rows } = await c.from("legal_documents").select("document_key,version,title,content,content_hash").eq("is_current", true).order("document_key"); setDocs((rows ?? []) as Doc[]); }); }, []);
  const ready = docs.length === 3 && read.length === 3 && checks.length === 3 && aiCoaching;
  async function confirm() { const c = createBrowserSupabaseClient(); const { data } = await c.auth.getUser(); if (!data.user) return; setStatus("Guardando…"); const { error } = await c.rpc("accept_current_legal_documents"); if (error) return setStatus("No pudimos registrar tu aceptación."); const { error: consentError } = await c.rpc("set_processing_consents", { p_ai_coaching: aiCoaching, p_weekly_journal_summary: weeklySummary, p_voice_transcription: voice, p_photo_ai_processing: photoAi }); if (consentError) return setStatus("No pudimos registrar tus preferencias de privacidad."); const { data: athleteProfile } = await c.from("athlete_profiles").select("onboarding_completed_at").eq("user_id", data.user.id).maybeSingle(); location.assign(athleteProfile?.onboarding_completed_at ? "/app" : "/onboarding"); }
  return <main className="legal-page"><section className="legal-shell"><p className="eyebrow">COMPROMISO ÉTICO & LEGAL</p><h1>Antes de empezar, construyamos un acuerdo claro.</h1><p>Leé los tres documentos y desplazate hasta el final de cada uno para continuar.</p><div className="legal-progress">{read.length} de 3 documentos revisados</div><div className="document-list">{docs.map((doc) => <article key={doc.document_key} className={read.includes(doc.document_key) ? "read" : ""}><button type="button" onClick={() => setOpen(open === doc.document_key ? null : doc.document_key)}><span>{read.includes(doc.document_key) ? "✓" : "0" + (docs.indexOf(doc) + 1)}</span>{doc.title}<b>{open === doc.document_key ? "−" : "+"}</b></button>{open === doc.document_key && <div className="document-content" onScroll={(event) => { const el = event.currentTarget; if (el.scrollTop + el.clientHeight >= el.scrollHeight - 4 && !read.includes(doc.document_key)) setRead([...read, doc.document_key]); }}><p>{doc.content}</p><small>Desplazate hasta el final para marcar este documento como leído.</small></div>}</article>)}</div><section className="consent-card"><h2>Validación de consentimiento</h2>{docs.map((doc) => <label key={doc.document_key}><input disabled={!read.includes(doc.document_key)} type="checkbox" checked={checks.includes(doc.document_key)} onChange={() => setChecks(checks.includes(doc.document_key) ? checks.filter((key) => key !== doc.document_key) : [...checks, doc.document_key])} />Acepto {doc.title} — versión {doc.version}.</label>)}<h2>Preferencias de procesamiento</h2><label><input type="checkbox" checked={aiCoaching} onChange={event => setAiCoaching(event.target.checked)} />Autorizo el acompañamiento con IA para mis conversaciones.</label><label><input type="checkbox" checked={weeklySummary} onChange={event => setWeeklySummary(event.target.checked)} />Autorizo un resumen semanal de mi bitácora.</label><label><input type="checkbox" checked={voice} onChange={event => setVoice(event.target.checked)} />Autorizo la transcripción de voz en este dispositivo.</label><label><input type="checkbox" checked={photoAi} onChange={event => setPhotoAi(event.target.checked)} />Autorizo procesar fotos con IA si esa función se habilita.</label><button className="auth-submit" disabled={!ready} onClick={confirm}>{ready ? "Confirmar mi compromiso →" : "Leé los documentos y autorizá el acompañamiento con IA"}</button>{status && <p>{status}</p>}</section></section></main>;
}
