"use client";
import { useEffect, useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
type Doc = { document_key: "terms" | "privacy" | "ai_use"; version: string; title: string; content: string; content_hash: string };
export function TermsFlow() {
  const [docs, setDocs] = useState<Doc[]>([]); const [open, setOpen] = useState<string | null>(null); const [read, setRead] = useState<string[]>([]); const [checks, setChecks] = useState<string[]>([]); const [status, setStatus] = useState("");
  useEffect(() => { const c = createBrowserSupabaseClient(); void c.auth.getUser().then(async ({ data }) => { if (!data.user) return location.assign("/access"); const { data: rows } = await c.from("legal_documents").select("document_key,version,title,content,content_hash").order("document_key"); setDocs((rows ?? []) as Doc[]); }); }, []);
  const ready = docs.length === 3 && read.length === 3 && checks.length === 3;
  async function confirm() { const c = createBrowserSupabaseClient(); const { data } = await c.auth.getUser(); if (!data.user) return; setStatus("Guardando…"); const rows = docs.map((doc) => ({ user_id: data.user!.id, document_key: doc.document_key, document_version: doc.version, document_hash: doc.content_hash, read_at: new Date().toISOString() })); const { error } = await c.from("terms_acceptances").upsert(rows, { onConflict: "user_id,document_key,document_version" }); if (error) return setStatus("No pudimos registrar tu aceptación."); location.assign("/onboarding"); }
  return <main className="legal-page"><section className="legal-shell"><p className="eyebrow">COMPROMISO ÉTICO & LEGAL</p><h1>Antes de empezar, construyamos un acuerdo claro.</h1><p>Leé los tres documentos y desplazate hasta el final de cada uno para continuar.</p><div className="legal-progress">{read.length} de 3 documentos revisados</div><div className="document-list">{docs.map((doc) => <article key={doc.document_key} className={read.includes(doc.document_key) ? "read" : ""}><button type="button" onClick={() => setOpen(open === doc.document_key ? null : doc.document_key)}><span>{read.includes(doc.document_key) ? "✓" : "0" + (docs.indexOf(doc) + 1)}</span>{doc.title}<b>{open === doc.document_key ? "−" : "+"}</b></button>{open === doc.document_key && <div className="document-content" onScroll={(event) => { const el = event.currentTarget; if (el.scrollTop + el.clientHeight >= el.scrollHeight - 4 && !read.includes(doc.document_key)) setRead([...read, doc.document_key]); }}><p>{doc.content}</p><small>Desplazate hasta el final para marcar este documento como leído.</small></div>}</article>)}</div><section className="consent-card"><h2>Validación de consentimiento</h2>{docs.map((doc) => <label key={doc.document_key}><input disabled={!read.includes(doc.document_key)} type="checkbox" checked={checks.includes(doc.document_key)} onChange={() => setChecks(checks.includes(doc.document_key) ? checks.filter((key) => key !== doc.document_key) : [...checks, doc.document_key])} />Acepto {doc.title} — versión {doc.version}.</label>)}<button className="auth-submit" disabled={!ready} onClick={confirm}>{ready ? "Confirmar mi compromiso →" : "Leé los 3 documentos para continuar"}</button>{status && <p>{status}</p>}</section></section></main>;
}
